release.key_file=../keystore/caller.jks
release.key_alias=caller
release.store_password=123456
release.key_password=123456

debug.key_file=../keystore/caller.jks
debug.key_alias=caller
debug.store_password=123456
debug.key_password=123456